// Auto-generated by contracts/scripts/createMarkets.js after deployment.
// Until the contract is deployed this file keeps the app running in API-fallback mode.

const deployment = {
  address: import.meta.env.VITE_CONTRACT_ADDRESS ?? null,
  cUSD:    import.meta.env.VITE_CUSD_ADDRESS    ?? '0x874069Fa1Eb16D44d622F2e0Ca25eeA172369bC1',
  chainId: 44787,
  marketMappings: {},
  abi: [
    "function createMarket(string question, uint256 closeTime, bool hasDraw) returns (uint256)",
    "function placeBet(uint256 id, uint8 outcome, uint256 amount)",
    "function resolveMarket(uint256 id, uint8 result)",
    "function cancelMarket(uint256 id)",
    "function claimWinnings(uint256 id)",
    "function claimRefund(uint256 id)",
    "function getOdds(uint256 id) view returns (uint256 yesOdds, uint256 noOdds, uint256 drawOdds)",
    "function getMarket(uint256 id) view returns (string question, uint256 closeTime, uint8 status, uint8 result, bool hasDraw, uint256 yesPool, uint256 noPool, uint256 drawPool, uint256 totalPool)",
    "function getBet(uint256 id, address bettor) view returns (uint256 amount, uint8 outcome, bool claimed)",
    "function marketCount() view returns (uint256)",
    "event BetPlaced(uint256 indexed id, address indexed bettor, uint8 outcome, uint256 amount)",
    "event MarketResolved(uint256 indexed id, uint8 result)",
    "event WinningsClaimed(uint256 indexed id, address indexed bettor, uint256 payout)",
  ],
};

export default deployment;
